### ISSUE TITLE
No use of 'private' roads according to 'wegenregister'

### ISSUE THREAD

**Issue by StijnClaes** [osmbe/road-completion#12]
See news item of the 28th of April 2020 on https://verkeersborden.vlaanderen/
MOW-AWV applied an algorithm to identify private roads (OSM tag access = private) in the 'wegenregister' as it was bothering their speed algorithm. I think (but I'm not 100% sure) the results of this algorithm were integrated in the latest versions of the 'Wegenregister'. 

It could be considered to apply TGBEP != 4 to the filter applied on the 'Wegenregister' in order to leave those private roads out of the road completion project (or at least focus on the other ones).

**Comment by jbelien** [comment]
Hello @StijnClaes ,

`TGBEP` (_Toegangsbeperking_) is alreay taken into account in the process : we tag it indeed as `access=private` (see https://github.com/osmbe/road-completion/tree/master/data/belgium/flanders#tgbep-toegangsbeperking)

I need to update the _wegenregister_ (version 17/12/2020).
I'll check how many of `TGBEP = 4` there are.

**Comment by StijnClaes** [comment]
So they are appearing as potential issues in the road completion project (MapRoulette). My suggestion would be to leave them out for the moment and focus on the other ones.

Furthermore, if you add them, maybe it should be considered to indicate somehow in MapRoulette that the tag `access=private` probably should apply. Now a contributor can only see this by clicking on the blue road segment (which I only saw now provides the attributes from the _wegenregister_)

**Comment by jbelien** [comment]
> My suggestion would be to leave them out for the moment and focus on the other ones.

I've updated _wegenregister_ and checked how many `TGBEP = 4` there are : only 128 (on 6501 missing segments).
I don't think it's worth filtering it out.

> Furthermore, if you add them, maybe it should be considered to indicate somehow in MapRoulette that the tag access=private probably should apply. Now a contributor can only see this by clicking on the blue road segment (which I only saw now provides the attributes from the wegenregister)

You're absolutely right !
Unfortunately, I don't see a way to do that in MapRoulette at the moment.

**Comment by StijnClaes** [comment]
Strange! I've asked my contact person at Snelheid.Vlaanderen whether the results of their algorithm maybe were not taken up in the _wegenregister_. I'll keep you informed.

**Comment by jbelien** [comment]
For now, we only keep the segments from _wegenregister_ that have a name (see [`filter.sql`](https://github.com/osmbe/road-completion/blob/master/data/belgium/flanders/filter.sql)). I'm guessing most of `TGBEP = 4` do not have a name.

**Comment by StijnClaes** [comment]
Indeed, that's correct.

**Comment by joostschouppe** [comment]
Maybe the people at snelheid.vlaanderen used "has no name" as well to find private roads; or they removed the name from private roads they found. Total number of cases only went down by a few hundred, so I hope they still are working on this topic...

**Comment by joostschouppe** [comment]
There seem to be no actions needed at this point, but feel free to re-open as news comes up
