### ISSUE TITLE
PICC road data

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/road-completion#2]
## How to get the data?
Road data available from [PICC](http://geoportail.wallonie.be/catalogue/b795de68-726c-4bdf-a62a-a42686aa5b6f.html)
You need to jump through a few hoops, and then get a downloadable file.

## Are we allowed to use the data?
After reading https://wiki.openstreetmap.org/wiki/WikiProject_Belgium/Mapping_resources/SPW#PICC_general_access_and_conditions_clarified_in_English I don't think we can simply use the data.
However, the download application process is pretty straightforward - if we try to download and explain exaclty what we want to do, and they allow it, we should be in the clear

## Is the data usefull?

The data is a little weird: it contains both "axe" (centerlines) and "ligne" (outline). However, often one of both is missing. If you just use axe, you will have floating bits of road all over the place
![afbeelding](https://user-images.githubusercontent.com/10122639/94257668-f0644080-ff2b-11ea-8d71-0405501e9185.png)

However, a relatively cursory glance already turned up this are of missing roads: 
![afbeelding](https://user-images.githubusercontent.com/10122639/94258117-a891e900-ff2c-11ea-83a5-da9e074f8209.png)

## Do we need to filter the data?
TODO

**Comment by jbelien** [comment]
So, should we use PICC data or not ? 😁
Should we contact them before using it ?

**Comment by joostschouppe** [comment]
Yes, I think we should give it a shot

> Yes, we need to ask first
We should also ask some of our Wallonian friends to look into possible
filters.

**Comment by joostschouppe** [comment]
License seems to be OK, see https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf (as linked here http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b795de68-726c-4bdf-a62a-a42686aa5b6f)
