### ISSUE TITLE
Addition of a new dataset from Luxembourg

### ISSUE THREAD

**Issue by DavidMoraisFerreira** [osmbe/road-completion#3]
Hello neighbors,

We have a potentially interesting dataset in Luxembourg that contains street geometry and is updated on a weekly basis [(TRP-VC)](https://data.public.lu/en/datasets/transport-et-voies-de-communication/). This could be a success story for your project, as it would add another dataset to your existing ones and demonstrate to the wider community that the tool is not only restricted to Belgian datasets. I would be willing to serve as a stakeholder and also help where needed with the implementation that would enable us to process our dataset. Perhaps this could also serve to identify what documentation is needed to assist other interested parties.

The aforementioned dataset is licensed under Creative Commons Zero (CC0) and contains information about the classification, surface and state of the streets. 

@grischard: do you know how good the quality of this dataset is?

**Comment by jbelien** [comment]
Now that the process is almost ready, I will need some information :

- Should I apply a filter on the data before processing ? (see [flanders](https://github.com/osmbe/road-completion/blob/master/data/belgium/flanders/filter.sql) for reference)
- What fields can be converted to OSM tags and how ? (see [flanders](https://github.com/osmbe/road-completion/blob/master/data/belgium/flanders/convert.json) for reference)

Documentation will be extended soon but you can already use [Flanders README](https://github.com/osmbe/road-completion/tree/master/data/belgium/flanders) as reference.

**Comment by grischard** [comment]
Filter: https://github.com/osmlu/csventrifuge is what we've built locally to filter the data. Maybe id_rue_cac can be used as a foreign key for the name. @dmlu is https://dmlu.dev.openstreetmap.org/luxaddr/ the right place to grab the translated strings from?

Fields: There's a description of the attributes at https://download.data.public.lu/resources/transport-et-voies-de-communication/20190405-105709/trp-vc-description-attributs.xlsx but it doesn't say what the fields can actually contain...

**Comment by DavidMoraisFerreira** [comment]
Hi,
@grischard yes, that folder contains the results of csventrifuge (daily cron). Good idea with the foreign key!
@jbelien Thank you for the useful pointers, I began adding the data set [here](https://github.com/DavidMoraisFerreira/road-completion/tree/luxembourg_trp_vc).

With regards to the field values, I opened a [discussion thread](https://data.public.lu/fr/datasets/transport-et-voies-de-communication/#discussion-5f8eaf59afb9f632fb786a0d) to get some more details on the data set. Unfortunately, I don't think we will get very detailed OSM tags from the data set, as it seems very incomplete ("non codé" in a lot of places).

**Comment by jbelien** [comment]
@DavidMoraisFerreira Road Completion is up and running for Belgium. Do you need some help to merge Luxembourg ?

**Comment by DavidMoraisFerreira** [comment]
> 
> 
> @DavidMoraisFerreira Road Completion is up and running for Belgium. Do you need some help to merge Luxembourg ?

Hi! Apologies for the late reply, I have a busy week ahead of me.

I'll try to implement the remaining parts this weekend. If I get stuck somewhere I'll let you know :) On the upside, the attributes from the dataset are now [documented](https://data.public.lu/fr/datasets/transport-et-voies-de-communication/#discussion-5f8eaf59afb9f632fb786a0d-1).
