### ISSUE TITLE
next steps - turn "too hard" tasks into OSM Notes with a survey request

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/road-completion#6]
This could also be just a manual job

But for now it's a little annoying that maproulette keeps brining up these tasks that are marked as "too hard" to the same or other mappers

**Comment by jbelien** [comment]
Indeed, at the moment, the "Too hard" issues are just not used in the data process (only process the tasks marked as "Not an issue").

I could also include the issues marked as "Too hard" in the data process (would be considered as "false positive") and export those in a separate GeoJSON file.
Would that make sense ?

**Comment by joostschouppe** [comment]
Yes, that would be close to perfect.
If I understand correctly, the "too hard" tasks would then automatically disappear from the main maproulette task.
The extra geojson with just the "hard stuff" could be shown in a separate maproulette tasks (flagged with "local knowledge required"; that exists in maproulette)

I just wonder how to handle this long term. It will take a while to get them fixed. As long as the task isn't handled, it needs to be excluded from the main process. If they get mapped, then the exception is no longer needed. If it turns out to be "not an issue", then it needs to be excluded permanently. So you would now have two feedback loops - that sounds annoying.

A very minor issue is that the tasks do remain visible for as long as the data hasn't been re-processed. That's a pure Maproulette issue though. It does mean that "when you try to clean out your neighborhood", you will stumble upon these tasks again and again until you wait for the data processing to re-run

**Comment by joostschouppe** [comment]
I just thought of an alternative workflow:
- ask mappers to add "too hard" tasks anyway with a tag like `fixme=road completion suggests a road here, please survey` and a special tag to make sure we can find them all back, like `fixme:roadcompletion=yes`. Then they can show up in Osmand, StreetComplete or Mapcomplete for mapping on the road!
- consider "too hard" tasks the same as "false positives" for the processing

The only issue is some people not reading the instructions and using "too hard" without mapping a "possible road". So it might be good to ignore the "too hard" tasks after a longer while (say a year), but still exclude them from the process by adding ways with `fixme:roadcompletion=yes` to the osm-highway dataset. If the survey said "not a highway", we still have a problem though - we could ask to leave them in as `fixme:roadcompletion=no` :)

**Comment by jbelien** [comment]
Not a big fan of mapping something we're not sure about ; especially when it could be a false positive.

I would suggest to keep a separate GeoJSON file with all the "roads" marked as "Too hard" (and include that file in the process) AND create a note (content still to be defined).

**Comment by jbelien** [comment]
In the end, it's more simple than expected.

The "Too hard" tasks were not deleted when I rebuilt the tasks, they were duplicated because I didn't define a unique ID for each tasks.
Each tasks has now a unique ID (from the source) and when I rebuild the tasks, if a task already has a status (like "Too hard") it will not be created again.
When we have dealt with all the tasks, we can focus on the "Too hard" tasks (better aerial imagery, create notes, ...).
