### ISSUE TITLE
visualize stats

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/road-completion#8]
Of course the Maproulette task has some stats
But it is limited: the total number of tasks can drop unceremoniously every time the challenge is refreshed

The process writes a stats file, which can be useful for longer term visualization.
The stats file versions could be used to plot a graph over time AND to make a map of the number of missing roads per tile

It is possible to have the history of a file programmaticaly, e.g. : https://api.github.com/repos/osmbe/road-completion/commits?path=data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/stats.json
and https://api.github.com/repos/osmbe/road-completion/contents/data/belgium/flanders/difference/Wegenregister_SHAPE_20200917/stats.json?ref=6f63f0820b5db0d1769773f473a1b54933d5f782 to get the content at a certain stage

**Comment by jbelien** [comment]
First version: <https://osmbe.github.io/road-completion/> 🚀

**Comment by joostschouppe** [comment]
This is awesome!

**Comment by jbelien** [comment]
- ✨ Chart added
- Limit of 3 commits removed
- Link to view `diff.geojson` files
